# Built with Jekyll 3.2.0

# Setup
title:               Deryk Makgill
tagline:             'a jekyll theme for minimal editions'
description:         'Ed is a Jekyll theme designed for textual editors based on minimal computing principles, and focused on legibility and flexibility.'
baseurl:             ''

# About/contact
author:
  name:              Alex Gil
  url:               https://twitter.com/elotroalex
  email:             colibri.alex@gmail.com

# Permalinks
permalink: pretty
 

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  
paginate_path: "/blog/:num/"

paginate: 10
